# Site settings
theme: jekyll-theme-minimal
classes: wide 
layout: default
title: Work Plans
logo: /Folder/download (1).png
show_date: true
read_time: true
search: true
description: <h2><strong>Event Plan</strong></h2>
             <p>Monday 10:00 - description</p>
             <p>Tuesday 10:00 - description</p>
             <p>Wednseday 10:00 - description</p>
             <a href="https://us02web.zoom.us/meeting/register/tZctdOyhqT4tH9DubmQ3qKwI8_s1lxkQ4xhx">Registration Form</a>
show_downloads: false
# Navigation Menus
header_navigation:
  - title: Documentation
    url: /docs/

  - title: Themes
    url: https://desiredpersona.com/themes/

  - title: About
    url: /about/

  - title: Blog
    url: /archive/
